define([
       'crafty',
       'game/entities/_base',
       'game/spriters/Player',
       'game/components/Walker'
], function(Crafty, BaseEntity, PlayerSpriter) {
  var Player = BaseEntity.extend({
    defaults: {
      spriter: new PlayerSpriter(),
      tile: 'south',
      // Center player by default.
      x: Crafty.viewport.width / 2,
      y: Crafty.viewport.height / 2,
      w: 32,
      h: 64
    },
    initialize: function() {
      var model = this;
      // Mind that the last component is generated by the sprite.
      model.get('spriter').create();
      // Initializing entity components.
      var entity = Crafty.e('Player, backboner, walker, DOM, 2D, Multiway, Collision')
      .addComponent(model.get('tile'))
      .backboner(model)
      .attr({
        x: model.get('x') - model.get('w'),
        y: model.get('y') - model.get('h'),
        w: model.get('w'),
        h: model.get('h')
      })
      // first arg is speed in pixels, second is dict of keys and directions in degrees (0 is right).
      .multiway(5, {W: -90, A: 180, S: 90, D: 0})
      .bind('Moved', function(from) {
        // Don't walk if it hits something solid.
        if (this.hit('solid')) {
          this.attr({x: from.x, y: from.y});
        }
      }).onHit('Enemy', function() {
        // Don't walk into the enemy, or else...
          this.destroy();
      });

      model.set({'entity': entity});
    },
  });

  return Player;
});
